// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAepxTV30LQmK5y9H4nzr8_KWcC4xpg7Mw',
    appId: '1:182294228382:web:c4c2b09bc6f1c08c693a8f',
    messagingSenderId: '182294228382',
    projectId: 'easygarden-3c6d4',
    authDomain: 'easygarden-3c6d4.firebaseapp.com',
    storageBucket: 'easygarden-3c6d4.firebasestorage.app',
    measurementId: 'G-3HVNDL5RD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASHuqhaDGLQ7xtYUkiwZ6EIePEFwhoTYQ',
    appId: '1:182294228382:android:df70948c7226e62c693a8f',
    messagingSenderId: '182294228382',
    projectId: 'easygarden-3c6d4',
    storageBucket: 'easygarden-3c6d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvMJSHgpz_AKVBqmX0sTovbkRto1hqzOE',
    appId: '1:182294228382:ios:c9766aa67a7b9e0a693a8f',
    messagingSenderId: '182294228382',
    projectId: 'easygarden-3c6d4',
    storageBucket: 'easygarden-3c6d4.firebasestorage.app',
    iosBundleId: 'com.example.easygarden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvMJSHgpz_AKVBqmX0sTovbkRto1hqzOE',
    appId: '1:182294228382:ios:c9766aa67a7b9e0a693a8f',
    messagingSenderId: '182294228382',
    projectId: 'easygarden-3c6d4',
    storageBucket: 'easygarden-3c6d4.firebasestorage.app',
    iosBundleId: 'com.example.easygarden',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAepxTV30LQmK5y9H4nzr8_KWcC4xpg7Mw',
    appId: '1:182294228382:web:9d330b51705678da693a8f',
    messagingSenderId: '182294228382',
    projectId: 'easygarden-3c6d4',
    authDomain: 'easygarden-3c6d4.firebaseapp.com',
    storageBucket: 'easygarden-3c6d4.firebasestorage.app',
    measurementId: 'G-R4CPDN8ZVW',
  );
}
